# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license
"""
Ultralytics neural network modules.

This module provides access to various neural network components used in Ultralytics models, including convolution
blocks, attention mechanisms, transformer components, and detection/segmentation heads.

Examples:
    Visualize a module with Netron
    >>> from ultralytics.nn.modules import Conv
    >>> import torch
    >>> import subprocess
    >>> x = torch.ones(1, 128, 40, 40)
    >>> m = Conv(128, 128)
    >>> f = f"{m._get_name()}.onnx"
    >>> torch.onnx.export(m, x, f)
    >>> subprocess.run(f"onnxslim {f} {f} && open {f}", shell=True, check=True)  # pip install onnxslim
"""

from .block import (
    C1,
    C2,
    C2PSA,
    C3,
    C3TR,
<<<<<<< HEAD
    C3k2_Dynamic,
    C3k2UltraPro,
    C3k2MA,
    C3k2MA_Lite,
    CIB,
    DFL,
    ELAN1,
    C2f_LSKA,
    WaveC2f,
    DyC2f,
    A3C2f,
=======
    CIB,
    DFL,
    DyC2f,
    DyMoEBlock,
    ELAN1,
>>>>>>> origin/main
    PSA,
    SPP,
    SPPELAN,
    SPPF,
    A2C2f,
    AConv,
    ADown,
    Attention,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C2fCIB,
    C2fPSA,
    C3Ghost,
    C3k2,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    MaxSigmoidAttnBlock,
    Proto,
    RepC3,
    RepNCSPELAN4,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    TorchVision,
)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    Index,
    LightConv,
    RepConv,
    SpatialAttention,
)
from .head import (
    OBB,
<<<<<<< HEAD
=======
    OBB26,
>>>>>>> origin/main
    Classify,
    Detect,
    LRPCHead,
    Pose,
<<<<<<< HEAD
    RTDETRDecoder,
    Segment,
    WorldDetect,
    YOLOEDetect,
    YOLOESegment,
=======
    Pose26,
    RTDETRDecoder,
    Segment,
    Segment26,
    SemanticSegment,
    WorldDetect,
    YOLOEDetect,
    YOLOESegment,
    YOLOESegment26,
>>>>>>> origin/main
    v10Detect,
)
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)
<<<<<<< HEAD
from .moa import MoABlock, C2fMoA, NeckMoAFusion, anneal_moa_temperature
from .mot import MoTBlock, C2fMoT, collect_mot_aux_loss, anneal_mot_temperature
from .moe import (
    OptimizedMOE,
    OptimizedMOEImproved,
    MOE,
    ES_MOE,
    EfficientSpatialRouterMoE,
    ModularRouterExpertMoE,
    UltraOptimizedMoE,
    AdaptiveCapacityMoE,
    HyperSplitMoE,
    HyperFusedMoE,
    HyperUltimateMoE,
    UltimateOptimizedMoE,
    AdaptiveGateMoE,
    DualStreamGateRouter,
    FusedAdaptiveGateMoE,
    HybridAdaptiveGateMoE,
    LowRankHybridAdaptiveGateMoE,
    RefinedLowRankHybridAdaptiveGateMoE,
    VisualDetailGate,
    PyramidContextMixer,
    DetailAwareLowRankHybridAdaptiveGateMoE,
    ContextRefinedLowRankHybridAdaptiveGateMoE,
    VisualEnhancedAdaptiveGateMoE,
    A2C2fMoE,
    ABlockMoE,
    SharedExpertMoE,
)
=======
from .moa import C2fMoA, MoABlock, NeckMoAFusion, anneal_moa_temperature, collect_moa_aux_loss
from .moe import (
    A2C2fMoE,
    ABlockMoE,
    AdaptiveGateMoE,
    DetailAwareLowRankHybridAdaptiveGateMoE,
    DiversifiedExpertMoE,
    ES_MOE,
    FusedAdaptiveGateMoE,
    GatedFusionMoE,
    HybridAdaptiveGateMoE,
    HybridAdaptiveGateMoEv2,
    LowRankHybridAdaptiveGateMoE,
    ModularRouterExpertMoE,
    MultiHeadRouterMoE,
    OptimalHybridGateMoE,
    RefinedLowRankHybridAdaptiveGateMoE,
    UltimateOptimizedMoE,
    UltraOptimizedMoE,
    VisualEnhancedAdaptiveGateMoE,
)
from .mot import C2fMoT, MoTBlock, anneal_mot_temperature, collect_mot_aux_loss
from .latent_mixture import DenseChannelExpert, LatentMixture, LatentRouter, LatentRoutingContext, MultiScaleLatentMixture
>>>>>>> origin/main

__all__ = (
    "AIFI",
    "C1",
    "C2",
    "C2PSA",
    "C3",
    "C3TR",
<<<<<<< HEAD
    "C3k2_Dynamic",
    "C3k2UltraPro",
    "C3k2MA",
    "C3k2MA_Lite",
    "CBAM",
    "CIB",
    "DFL",
    "ELAN1",
    "MLP",
    "OBB",
=======
    "CBAM",
    "CIB",
    "DFL",
    "DyC2f",
    "DyMoEBlock",
    "ELAN1",
    "MLP",
    "OBB",
    "OBB26",
>>>>>>> origin/main
    "PSA",
    "SPP",
    "SPPELAN",
    "SPPF",
    "A2C2f",
    "AConv",
    "ADown",
    "Attention",
    "BNContrastiveHead",
    "Bottleneck",
    "BottleneckCSP",
    "C2f",
    "C2fAttn",
    "C2fCIB",
    "C2fPSA",
<<<<<<< HEAD
    "C2f_LSKA",
    "WaveC2f",
    "DyC2f",
    "A3C2f",
=======
>>>>>>> origin/main
    "C3Ghost",
    "C3k2",
    "C3x",
    "CBFuse",
    "CBLinear",
    "ChannelAttention",
    "Classify",
    "Concat",
    "ContrastiveHead",
    "Conv",
    "Conv2",
    "ConvTranspose",
    "DWConv",
    "DWConvTranspose2d",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "Detect",
    "Focus",
    "GhostBottleneck",
    "GhostConv",
    "HGBlock",
    "HGStem",
    "ImagePoolingAttn",
    "Index",
    "LRPCHead",
    "LayerNorm2d",
    "LightConv",
    "MLPBlock",
    "MSDeformAttn",
    "MaxSigmoidAttnBlock",
    "Pose",
<<<<<<< HEAD
=======
    "Pose26",
>>>>>>> origin/main
    "Proto",
    "RTDETRDecoder",
    "RepC3",
    "RepConv",
    "RepNCSPELAN4",
    "RepVGGDW",
    "ResNetLayer",
    "SCDown",
    "Segment",
<<<<<<< HEAD
=======
    "Segment26",
    "SemanticSegment",
>>>>>>> origin/main
    "SpatialAttention",
    "TorchVision",
    "TransformerBlock",
    "TransformerEncoderLayer",
    "TransformerLayer",
    "WorldDetect",
    "YOLOEDetect",
    "YOLOESegment",
<<<<<<< HEAD
    "v10Detect",
    "OptimizedMOE",
    "OptimizedMOEImproved",
    "MOE",
    "EfficientSpatialRouterMoE",
    "ModularRouterExpertMoE",
    "ES_MOE",
    "UltraOptimizedMoE",
    "AdaptiveCapacityMoE",
    "HyperSplitMoE",
    "HyperFusedMoE",
    "HyperUltimateMoE",
    "UltimateOptimizedMoE",
    "AdaptiveGateMoE",
    "DualStreamGateRouter",
    "FusedAdaptiveGateMoE",
    "HybridAdaptiveGateMoE",
    "LowRankHybridAdaptiveGateMoE",
    "RefinedLowRankHybridAdaptiveGateMoE",
    "VisualDetailGate",
    "PyramidContextMixer",
    "DetailAwareLowRankHybridAdaptiveGateMoE",
    "ContextRefinedLowRankHybridAdaptiveGateMoE",
    "VisualEnhancedAdaptiveGateMoE",
    "A2C2fMoE",
    "ABlockMoE",
    "SharedExpertMoE",
    "MoABlock",
    "C2fMoA",
    "NeckMoAFusion",
    "anneal_moa_temperature",
    "MoTBlock",
    "C2fMoT",
    "collect_mot_aux_loss",
    "anneal_mot_temperature",
=======
    "YOLOESegment26",
    "v10Detect",
    "A2C2fMoE",
    "ABlockMoE",
    "AdaptiveGateMoE",
    "C2fMoA",
    "C2fMoT",
    "DetailAwareLowRankHybridAdaptiveGateMoE",
    "DiversifiedExpertMoE",
    "ES_MOE",
    "FusedAdaptiveGateMoE",
    "GatedFusionMoE",
    "HybridAdaptiveGateMoE",
    "HybridAdaptiveGateMoEv2",
    "LowRankHybridAdaptiveGateMoE",
    "MoABlock",
    "MoTBlock",
    "ModularRouterExpertMoE",
    "MultiHeadRouterMoE",
    "NeckMoAFusion",
    "OptimalHybridGateMoE",
    "RefinedLowRankHybridAdaptiveGateMoE",
    "UltimateOptimizedMoE",
    "UltraOptimizedMoE",
    "VisualEnhancedAdaptiveGateMoE",
    "anneal_moa_temperature",
    "anneal_mot_temperature",
    "collect_moa_aux_loss",
    "collect_mot_aux_loss",
    "DenseChannelExpert",
    "LatentMixture",
    "LatentRouter",
    "LatentRoutingContext",
    "MultiScaleLatentMixture",
>>>>>>> origin/main
)
